server:
  port: 8087

spring:
  application:
    name: sim-service

  datasource:
    url: jdbc:mysql://localhost:3306/telecom_db
    username: root
    password: Nimai@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
