#server:
#  port: 8085
#
#spring:
#  application:
#    name: API-GATEWAY
#
#  cloud:
#    gateway:
#
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
#            allowedHeaders: "*"
#
#      routes:
#
#        - id: auth-service
#          uri: lb://AUTH-SERVICE
#          predicates:
#            - Path=/auth/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: authCircuitBreaker
#                fallbackUri: forward:/fallback/auth
#
#        - id: sim-service
#          uri: lb://SIM-SERVICE
#          predicates:
#            - Path=/sim/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: simCircuitBreaker
#                fallbackUri: forward:/fallback/sim
#
#        - id: kyc-service
#          uri: lb://KYC-SERVICE
#          predicates:
#            - Path=/kyc/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: kycCircuitBreaker
#                fallbackUri: forward:/fallback/kyc
#
#        - id: notification-service
#          uri: lb://NOTIFICATION-SERVICE
#          predicates:
#            - Path=/notification/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: notificationCircuitBreaker
#                fallbackUri: forward:/fallback/notification
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true
#
#jwt:
#  secret: mySuperSecretKey123456
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#logging:
#  level:
#    org.springframework.cloud.gateway: INFO
server:
  port: 8085

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: false

      routes:

        - id: auth-service
          uri: lb://AUTH-SERVICE

          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/auth

        - id: sim-service
          uri: lb://SIM-SERVICE
          predicates:
            - Path=/sim/**
          filters:
            - name: CircuitBreaker
              args:
                name: simCircuitBreaker
                fallbackUri: forward:/fallback/sim

        - id: kyc-service
          uri: lb://KYC-SERVICE
          predicates:
            - Path=/kyc/**
          filters:
            - name: CircuitBreaker
              args:
                name: kycCircuitBreaker
                fallbackUri: forward:/fallback/kyc

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**
          filters:
            - name: CircuitBreaker
              args:
                name: notificationCircuitBreaker
                fallbackUri: forward:/fallback/notification

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: mySuperSecretKey123456

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: INFO
